# Generated by Django 4.1.7 on 2023-03-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('titles', models.PositiveIntegerField(null=True)),
                ('top_scorer', models.CharField(max_length=50)),
                ('fifa_code', models.CharField(max_length=3, unique=True)),
                ('first_cup', models.DateField(null=True)),
            ],
        ),
    ]
