# Generated by Django 4.1.7 on 2023-03-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='titles',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
