# Generated by Django 4.1.7 on 2023-04-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
